### ISSUE TITLE
"//" parses an unterminated string followed by a end-of-line comment

### ISSUE THREAD

**Issue by nordlow** [gdamore/tree-sitter-d#40]
The statement

```d
immutable x = "//";
```

doesn't parse

```d
`"//"`
```

as a complete string but as unterminated string because `//` has higher priority than second terminating `"`.

**Comment by gdamore** [comment]
Thanks... will look.

**Comment by gdamore** [comment]
I've been digging into this.  Its a regression and it is caused by the switch to use string parsing during parsing rather than lexing.  The reason I did that was that interpolated strings need full grammar support.  So the boundary between lexing (identifying tokens, and previously tokens were strings) is broken.

Comments really need to be collected during lexing because they are treated as a whitespace equivalent, otherwise we would have a really *crazy* grammar to permit comments to appear literally anywhere in the language.

I probably need to go back and have a rethink of the changes I made for interpolated strings.

As usual, D has added lots of syntactic sugar that makes this very much harder.  (Btw, I could probably handle these style comments without too much difficulty, but *nestable* comments of the form `/+ comment +/`  are a serious problem since they require being handled during the parse phase to support the nesting, which is incompatible with the simpler parsing.  So I'm not sure how to handle that.

If I could throw away '/+ +/' comments, everything here would be so much simpler.

**Comment by gdamore** [comment]
So I made some progress here, but haven't really *fixed* it.  The "fix" helps with comments in embedded strings, but only if they aren't the *start* of the string.  The problem is that when the strings moved to being in the parser, it somehow is allowing tokens to be used inside the string, and I think its a problem with how token.immediate() works.  I suspect it would go away if I could figure out how to make a terminal token version of '/+ +/' comments, but I have not been able to do figure that out yet ... the nesting sort of requires it either be treated in the grammar as a non-terminal grammar element, or I have to use the external scanner, which winds up overpowering the logic.

I might be able to just relegate the '/+' comments to the external scanner, and live with the ramifications that those comments won't work well in strings, but I'm not happy about that either.

**Comment by gdamore** [comment]
I have not.  I'm not even sure how'd phrase the question, and I doubt much I'd get an intelligible answer.
